### ISSUE TITLE
你这代码有冗余的地方

### ISSUE THREAD

**Issue by Junyi-99** [DaweiX/bilibili#1]
bilibili-master\bilibili\Helpers\ApiHelper.cs
第145行 if (code != 0)
你这里已经判断过code的值了，在第151行if (accesskey1 != string.Empty && code == 0)
你又判断了一下 code==0，虽然对性能无影响，但是我还是忍不住要提一下。。。

**Comment by DaweiX** [comment]
哈哈，多谢提醒啦
